GET https://api.harvardartmuseums.org/image?apikey=a3ea6ad7-34cb-4507-a771-21efbcd15181&q=name:18th century BCE

###
GET https://api.harvardartmuseums.org/image/326541?apikey=a3ea6ad7-34cb-4507-a771-21efbcd15181&

###
